apiVersion: v1
kind: Namespace
metadata:
  name: petest-ns

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: petest-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-petest.challenge
    http:
      paths:
      - path: /
        backend:
          serviceName: petest-svc
          servicePort: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petest-app
  namespace: petest-ns
spec:
  selector:
    matchLabels:
      run: petest-app
  replicas: 1
  template:
    metadata:
      labels:
        run: petest-app
    spec:
      containers:
      - name: petest-app
        image: petest-app-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3        
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3           
          

---
kind: Service
apiVersion: v1
metadata:
  name: petest-svc
  namespace: petest-ns
  labels:
    run: petest-app
spec:
  selector:
    run: petest-app
  type: NodePort  
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001